makamproject/makam_app/urls.py
from django.urls import path, include
from . import views

app_name = 'makam_app'

urlpatterns = [
    path('', views.HomeView, name='HomeView'),
    path('create_piece/', views.CreatePieceView, name='CreatePieceView'),
    path('find_piece/', views.FindPieceView, name='FindPieceView'),
    path('query_results/', views.QueryResultsView, name='QueryResultsView'),
    path('analysis/', views.AnalysisView, name='AnalysisView'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('profile/', views.UserPieceView.as_view(), name='profile'),
    path('edit/<int:pk>', views.EditPieceView, name='EditPieceView'),
    path('delete/<int:pk>', views.delete_piece, name='delete_piece'),
]

makamproject/makamproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('makam_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

makamproject/makamproject/templates/base.html
<!doctype html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Makam</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    .nav-link {
      color: black;
      font-size: 18px;
      /* font-weight: bold; */
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="container-fluid">

      <div class="col-1">
        <a class="navbar-brand">
          <img src="{% static 'itu_logo.jpg' %}" width="40" height="40" alt="itu_logo">
        </a>
      </div>

      <div class="col-11">
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'makam_app:HomeView' %}">Anasayfa</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'makam_app:profile' %}">Profil</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'makam_app:CreatePieceView' %}">Parça Ekle</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'makam_app:FindPieceView' %}">Parça Ara</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}?next={{request.path}}">Çıkış Yap</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}?next={{request.path}}">Giriş Yap</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'makam_app:signup' %}">Kaydol</a>
            </li>
            {% endif %}
          </ul>
        </div>
  </nav>

  <div class="container mt-3">
    {% block content %}
    {% endblock content %}
  </div>

  <script src="https://code.jquery.com/jquery-3.6.1.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

  {% block scripts %}
  {% endblock scripts %}
</body>

</html>