makamproject/makam_app/urls.py
from django.urls import path, include
from . import views

app_name = 'makam_app'

urlpatterns = [
    path('', views.HomeView, name='HomeView'),
    path('create_piece/', views.CreatePieceView, name='CreatePieceView'),
    path('find_piece/', views.FindPieceView, name='FindPieceView'),
    path('query_results/', views.QueryResultsView, name='QueryResultsView'),
    path('analysis/', views.AnalysisView, name='AnalysisView'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('profile/', views.UserPieceView.as_view(), name='profile'),
    path('edit/<int:pk>', views.EditPieceView, name='EditPieceView'),
    path('delete/<int:pk>', views.delete_piece, name='delete_piece'),
]

makamproject/makamproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('makam_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

makamproject/makam_app/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User


class Makam(models.Model):
    name = models.CharField(max_length=127)

    def __str__(self):
        return self.name


class Usul(models.Model):
    name = models.CharField(max_length=127)

    def __str(self):
        return self.name


class Piece(models.Model):
    eser_adi = models.CharField(max_length=127)
    bestekar = models.CharField(max_length=127)
    yuzyil = models.IntegerField()
    gufte_yazari = models.CharField(max_length=127)
    gufte_vezin = models.CharField(max_length=127)
    gufte_nazim_bicim = models.CharField(max_length=127)
    gufte_nazim_tur = models.CharField(max_length=127)
    makam = models.JSONField()
    usul = models.JSONField()
    form = models.CharField(max_length=127)
    subcomponents = models.JSONField()
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_date = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return f"{self.pk} - {self.eser_adi} - {self.creator} tarafından {self.created_date} tarihinde eklendi."

makamproject/makam_app/forms.py
from django import forms

class PreliminaryDataEntryForm(forms.Form):
    eser_adi = forms.CharField()
    bestekar = forms.CharField()
    yuzyil = forms.IntegerField()
    gufte_yazari = forms.CharField()
    VEZIN_CHOICES = (
        ('', 'Yok'),
        ('aruz', 'Aruz'),
        ('serbest', 'Serbest'),
    )
    gufte_vezin = forms.ChoiceField(widget=forms.Select, choices= VEZIN_CHOICES)
    NZMBCM_CHOICES = (
        ('', 'Yok'),
        ('gazel', 'Gazel'),
        ('murabba', 'Murabba'),
        ('kaside', 'Kaside'),
    )
    gufte_nzmbcm = forms.ChoiceField(
        widget=forms.Select, choices=NZMBCM_CHOICES)
    NZMTUR_CHOICES = (
        ('', 'Yok'),
        ('munacat', 'Münacat'),
        ('naat', 'Naat'),
        ('tevhit', 'Tevhit'),
    )
    gufte_nzmtur = forms.ChoiceField(
        widget=forms.Select, choices=NZMTUR_CHOICES)
    

makamproject/makam_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import JsonResponse, HttpResponseForbidden, HttpResponseNotAllowed
from .forms import PreliminaryDataEntryForm
from .models import Makam, Usul, Piece
from django.templatetags.static import static
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView, DetailView, ListView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.core.exceptions import PermissionDenied
import datetime
import json

pseudo_context = {}


def HomeView(request):

    return render(request, 'makam_app/home.html')


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'makam_app/signup.html'


class UserPieceView(LoginRequiredMixin, ListView):
    model = Piece
    template_name = 'makam_app/profile.html'

    def get_queryset(self):
        if self.request.user.is_staff:
            return Piece.objects.all()
        else:
            return Piece.objects.filter(creator=self.request.user).all()


@login_required
@permission_required('makam_app.add_piece', raise_exception=True)
def CreatePieceView(request):

    if request.method == 'POST':

        newPiece = Piece(
            eser_adi=request.POST.get('eser_adi'),
            bestekar=request.POST.get('bestekar'),
            yuzyil=request.POST.get('yuzyil'),
            gufte_yazari=request.POST.get('gufte_yazari'),
            gufte_vezin=request.POST.get('gufte_vezin'),
            gufte_nazim_bicim=request.POST.get('gufte_nzmbcm'),
            gufte_nazim_tur=request.POST.get('gufte_nzmtur'),
            makam=json.loads(request.POST.get('selected_makams')),
            usul=json.loads(request.POST.get('selected_usuls')),
            form=json.loads(request.POST.get('selected_form')),
            subcomponents=json.loads(
                request.POST.get('selected_subcomponents')),
            creator=request.user,
            created_date=datetime.date.today(),
        )

        newPiece.save()

        return JsonResponse({
            'success': True,
            'url': reverse("makam_app:HomeView"),
        })

    else:

        preliminary_data_entry_form = PreliminaryDataEntryForm()

        context_dict = {
            'preliminary_data_entry_form': preliminary_data_entry_form,
            'mkm_json': json.dumps(list(Makam.objects.values())),
            'usl_json': json.dumps(list(Usul.objects.values())),
        }
        return render(request, 'makam_app/create_piece.html', context=context_dict)


@login_required
@permission_required('makam_app.change_piece', raise_exception=True)
def EditPieceView(request, pk):

    piece_to_be_edited = get_object_or_404(Piece, pk=pk)

    if request.method == 'POST':

        eser_adi = request.POST.get('eser_adi')
        bestekar = request.POST.get('bestekar')
        yuzyil = int(request.POST.get('yuzyil'))
        gufte_yazari = request.POST.get('gufte_yazari')
        gufte_vezin = request.POST.get('gufte_vezin')
        gufte_nazim_bicim = request.POST.get('gufte_nzmbcm')
        gufte_nazim_tur = request.POST.get('gufte_nzmtur')
        makam = json.loads(request.POST.get('selected_makams'))
        usul = json.loads(request.POST.get('selected_usuls'))
        form = json.loads(request.POST.get('selected_form'))
        subcomponents = json.loads(request.POST.get('selected_subcomponents'))

        piece_to_be_edited.eser_adi = eser_adi
        piece_to_be_edited.bestekar = bestekar
        piece_to_be_edited.yuzyil = yuzyil
        piece_to_be_edited.gufte_yazari = gufte_yazari
        piece_to_be_edited.gufte_vezin = gufte_vezin
        piece_to_be_edited.gufte_nazim_bicim = gufte_nazim_bicim
        piece_to_be_edited.gufte_nazim_tur = gufte_nazim_tur
        piece_to_be_edited.makam = makam
        piece_to_be_edited.usul = usul
        piece_to_be_edited.form = form
        piece_to_be_edited.subcomponents = subcomponents

        piece_to_be_edited.save()

        return JsonResponse({
            'success': True,
            'url': reverse("makam_app:profile"),
        })

    else:
        preliminary_data_entry_form = PreliminaryDataEntryForm()

        edit_piece_eser_adi = piece_to_be_edited.eser_adi
        edit_piece_bestekar = piece_to_be_edited.bestekar
        edit_piece_yuzyil = piece_to_be_edited.yuzyil
        edit_piece_gufte_yazari = piece_to_be_edited.gufte_yazari
        edit_piece_gufte_vezin = piece_to_be_edited.gufte_vezin
        edit_piece_gufte_nazim_bicim = piece_to_be_edited.gufte_nazim_bicim
        edit_piece_gufte_nazim_tur = piece_to_be_edited.gufte_nazim_tur
        edit_piece_makam = json.dumps(piece_to_be_edited.makam)
        edit_piece_usul = json.dumps(piece_to_be_edited.usul)
        edit_piece_form = piece_to_be_edited.form
        edit_piece_subcomponents = json.dumps(piece_to_be_edited.subcomponents)
        edit_piece_creator = piece_to_be_edited.creator
        edit_piece_created_date = piece_to_be_edited.created_date

    context_dict = {
        'preliminary_data_entry_form': preliminary_data_entry_form,
        'piece_to_be_edited': piece_to_be_edited,
        'edit_piece_eser_adi': edit_piece_eser_adi,
        'edit_piece_bestekar': edit_piece_bestekar,
        'edit_piece_yuzyil': edit_piece_yuzyil,
        'edit_piece_gufte_yazari': edit_piece_gufte_yazari,
        'edit_piece_gufte_vezin': edit_piece_gufte_vezin,
        'edit_piece_gufte_nazim_bicim': edit_piece_gufte_nazim_bicim,
        'edit_piece_gufte_nazim_tur': edit_piece_gufte_nazim_tur,
        'edit_piece_makam': edit_piece_makam,
        'edit_piece_usul': edit_piece_usul,
        'edit_piece_form': edit_piece_form,
        'edit_piece_subcomponents': edit_piece_subcomponents,
        'edit_piece_creator': edit_piece_creator,
        'edit_piece_created_date': edit_piece_created_date,
        'mkm_json': json.dumps(list(Makam.objects.values())),
        'usl_json': json.dumps(list(Usul.objects.values())),
    }

    return render(request, 'makam_app/edit_piece.html', context=context_dict)


@login_required
@permission_required('makam_app.delete_piece', raise_exception=True)
def delete_piece(request, pk):
    piece = get_object_or_404(Piece, pk=pk)

    if request.user.is_staff:
        if request.method == 'POST':
            piece.delete()
            return redirect('makam_app:profile')

    elif piece.creator != request.user:
        return HttpResponseForbidden()
    elif request.method == 'POST':
        piece.delete()
        return redirect('makam_app:profile')


@login_required
# @permission_required('makam_app.view_piece', raise_exception=True)
def FindPieceView(request):

    if request.method == 'POST':

        # query için verileri al
        eser_adi = request.POST.get('eser_adi')
        bestekar = request.POST.get('bestekar')
        yuzyil = request.POST.get('yuzyil')
        gufte_yazari = request.POST.get('gufte_yazari')
        gufte_vezin = request.POST.get('gufte_vezin')
        gufte_nazim_bicim = request.POST.get('gufte_nzmbcm')
        gufte_nazim_tur = request.POST.get('gufte_nzmtur')
        makam = json.loads(request.POST.get('selected_makams'))
        usul = json.loads(request.POST.get('selected_usuls'))
        form = json.loads(request.POST.get('selected_form'))
        subcomponents = json.loads(request.POST.get('selected_subcomponents'))

        pseudo_context['eser_adi'] = eser_adi
        pseudo_context['bestekar'] = bestekar
        pseudo_context['yuzyil'] = yuzyil
        pseudo_context['gufte_yazari'] = gufte_yazari
        pseudo_context['gufte_vezin'] = gufte_vezin
        pseudo_context['gufte_nazim_bicim'] = gufte_nazim_bicim
        pseudo_context['gufte_nazim_tur'] = gufte_nazim_tur
        pseudo_context['makam'] = makam
        pseudo_context['usul'] = usul
        pseudo_context['form'] = form
        pseudo_context['subcomponents'] = subcomponents

        # burada yukarıdaki verilere göre json query yap, gelenleri context ile queryresult'a yolla

        return JsonResponse({
            'success': True,
            'url': reverse("makam_app:QueryResultsView"),
        })

    else:
        preliminary_data_entry_form = PreliminaryDataEntryForm()

        context_dict = {
            'preliminary_data_entry_form': preliminary_data_entry_form,
            'mkm_json': json.dumps(list(Makam.objects.values())),
            'usl_json': json.dumps(list(Usul.objects.values())),
        }
        return render(request, 'makam_app/find_piece.html', context=context_dict)


selected_pieces_for_analysis = []


@login_required
# @permission_required('makam_app.view_piece', raise_exception=True)
def QueryResultsView(request):

    if request.method == 'POST':

        # buraya analiz için seçilen parçaların pk'ları gelecek, sonra o pk'ları filtre ile alıp analiz işlemini yapacağız
        # sonra da sonuçları yollayacağız

        selected_piece_pks = json.loads(request.POST.get('selected_pieces'))

        if len(selected_piece_pks) > 0:

            for my_pk in selected_piece_pks:

                my_piece = Piece.objects.get(pk=my_pk)

                if my_piece not in selected_pieces_for_analysis:
                    selected_pieces_for_analysis.append(my_piece)

            return JsonResponse({
                'success': True,
                'url': reverse("makam_app:AnalysisView"),
            })

        else:

            return JsonResponse({
                'success': False,
                'url': reverse("makam_app:QueryResultView"),
            })

    all_pieces = Piece.objects.all()

    filter_dict = {}

    for (key, value) in pseudo_context.items():

        # key: arama parametresi başlığı

makamproject/makam_app/templates/makam_app/analysis.html
{% extends "base.html" %}

{% load static %}

{% block title %}Analiz{% endblock title %}

{% block content %}

<h2>Seçilen Parçalardaki Bütün Bileşenlerin Özeti:</h2>
<br>
<div class="container">
    <div class="row">
        <ol id="analyzed_subcomponent_list">
        </ol>
    </div>
</div>

<br>

<!-- 
<hr>
<br> -->

<div style="opacity: 0%; pointer-events:none;" class="container">
    <h2>Parçaların Bileşenlerinin Analizleri: (Bu Özellik Iskartaya Çıkarıldı)</h2>
    <br>
    <div class="row">
        <ol id="analyzed_piece_list"></ol>
    </div>
</div>

{% endblock content%}

{% block scripts %}

<script>

    all_selected_pieces_data = '{{pieces|escapejs}}';

    pieces_cleaned_data = JSON.parse(all_selected_pieces_data);

    for (my_piece of pieces_cleaned_data) {

        let bilesen_name_list = [];
        let cesni_name_percentage_list = [];

        for (my_bilesen of my_piece['bilesenler']) {

            bilesen_name_list.push(my_bilesen['bilesen_ismi'])

            cesni_name_percentage_pair = {};

            for (my_cesni of my_bilesen['bilesen_cesniler']) {

                console.log(my_cesni);

                if (!(my_cesni['cesni_ismi'] in cesni_name_percentage_pair)) {

                    cesni_name_percentage_pair[my_cesni['cesni_ismi']] = my_cesni['cesni_oran'];
                }
                else {

                    cesni_name_percentage_pair[my_cesni['cesni_ismi']] += my_cesni['cesni_oran'];
                }
            }

            cesni_name_percentage_list.push(cesni_name_percentage_pair);
        }

        createNewChartAddToHtml(my_piece, bilesen_name_list, cesni_name_percentage_list)
    }

    function createNewChartAddToHtml(piece, bilesenler, cesniler) {

        my_piece_list = document.getElementById("analyzed_piece_list");

        current_li_name = String(piece['parca_ismi']);
        piece_list_item = document.createElement('li');
        piece_list_item.id = current_li_name;
        my_piece_list.appendChild(piece_list_item);

        for (let current_cesni_index = 0; current_cesni_index < cesniler.length; ++current_cesni_index) {

            console.log(cesniler);

            let data = [];
            let labels = [];

            for (key in cesniler[current_cesni_index]) {
                data.push(cesniler[current_cesni_index][key])
            }

            for (label in cesniler[current_cesni_index]) {
                labels.push(label)
            }

            current_chart_li_name = String(piece['parca_ismi']) + "_" + current_cesni_index + "_" + bilesenler[current_cesni_index];
            piece_chart_list = document.createElement('ul');
            piece_chart_list.id = current_chart_li_name;
            piece_list_item.appendChild(piece_chart_list);

            my_piece_list_node = document.getElementById(current_chart_li_name);

            current_chart_name = String(piece['parca_ismi'] + "_" + current_cesni_index + "_" + bilesenler[current_cesni_index] + "_" + 'piechart');
            current_cesni_list_name = String(piece['parca_ismi'] + "_" + current_cesni_index + "_" + bilesenler[current_cesni_index] + "_" + 'cesnilist');

            my_piece_list_node.insertAdjacentHTML('beforeend', `
            <li>
                 <div class="row">
                     <div class="col-5">
                        <em><b>Parça:</b></em> ${piece['parca_ismi']}
                        <br>
                        <br>
                        <em><b>Bileşen:</b></em> ${bilesenler[current_cesni_index]}
                        <br>
                        <br>
                        <em><b>Bileşendeki çeşnilerin usüllerine olan oranları:</b></em>
                        <br>
                        <br>
                        <ul id="${current_cesni_list_name}"></ul>
                     </div>
                     <div class="col-7">
                         <canvas width="200" height="200" id="${current_chart_name}"></canvas>
                     </div>
                 </div>
                 <hr>
                 <br>
             </li>
            `);

            var cesni_list_node = document.getElementById(current_cesni_list_name);

            for (let index = 0; index < data.length; index++) {

                let cesni_list_item = document.createElement('li');
                cesni_list_item.id = labels[index];
                cesni_list_item.innerHTML = labels[index] + ": % " + data[index];
                cesni_list_node.appendChild(cesni_list_item);

            }

            // console.log(cesni_list_node);

            var my_canvas = document.getElementById(current_chart_name).getContext('2d');

            colorArr = createColorArray(data.length)

            let my_chart = new Chart(my_canvas, {
                type: 'pie',
                data: {
                    labels: labels,
                    datasets: [{
                        data: data,
                        backgroundColor: colorArr,
                        borderColor: colorArr,
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    aspectRatio: 1,
                }
            });
        }

    }

    function createColorArray(length) {

        const colorArray = [];

        for (let i = 0; i < length; i++) {

            let color;
            do {
                const r = Math.floor(Math.random() * 256);
                const g = Math.floor(Math.random() * 256);
                const b = Math.floor(Math.random() * 256);
                const a = 100;

                color = `rgba(${r}, ${g}, ${b}, ${a})`;

            } while (color === 'rgba(255, 255, 255, 100)');

            colorArray.push(color);
        }

        return colorArray;
    }

    class Bilesen {
        constructor() {
            this._name = "";
            this._cesni_list = [];
        }

        set name(name) {
            this._name = name;
        }

        get name() {
            return this._name;
        }

        set cesni_list(cesni_list) {
            this._cesni_list = cesni_list;
        }

        get cesni_list() {
            return this._cesni_list;
        }
    }

    const b_list = [];

    for (const my_piece of pieces_cleaned_data) {

        for (const my_bilesen of my_piece["bilesenler"]) {

            const bilesen = new Bilesen();

            bilesen.name = my_bilesen["bilesen_ismi"];

            let bilesenExists = false;

            for (const b of b_list) {

                if (b.name === bilesen.name) {
                    bilesenExists = true;
                    break;
                }

            }

            if (!bilesenExists) {
                b_list.push(bilesen);
            }
        }
    }

    for (const b of b_list) {

        for (const my_piece of pieces_cleaned_data) {

            for (const my_bilesen of my_piece["bilesenler"]) {

                if (b.name === my_bilesen['bilesen_ismi']) {
                    for (const my_cesni of my_bilesen['bilesen_cesniler']) {
                        b.cesni_list.push(my_cesni);
                    }

                }

            }

        }

    }

    for (const b of b_list) {

        const modifiedCesniList = b._cesni_list.reduce((acc, curr) => {

            const { _name, _cesni_list } = curr;

            const modifiedCesniList = b._cesni_list.reduce((cesniAcc, cesni) => {

                const { cesni_ismi } = cesni;

                if (!cesniAcc[cesni_ismi]) {

                    cesniAcc[cesni_ismi] = {
                        cesni_ismi,
                        cesni_usul: cesni.cesni_usul,
                        cesni_sure_256: cesni.cesni_sure_256,
                        cesni_oran: cesni.cesni_oran
                    };

                } else {
                    cesniAcc[cesni_ismi].cesni_sure_256 += cesni.cesni_sure_256;
                }
                return cesniAcc;

            }, {});

            return { ...acc, ...modifiedCesniList };

        }, {});

        const modifiedCesniListArray = Object.values(modifiedCesniList);

        b._cesni_list = modifiedCesniListArray;
    }

    function createNewChartForSubcomponentAddToHtml(subcomponent_list) {

        my_subcomponent_list = document.getElementById("analyzed_subcomponent_list");

        for (const s of subcomponent_list) {

            data = [];
            labels = [];

            for (const cesni of s._cesni_list) {

                data.push(cesni.cesni_sure_256);
                labels.push(cesni.cesni_ismi);

            }

            my_percentage_data = toPercentages(data);

            current_li_name = String(s._name) + '_subcomponent';

            subcomponent_list_item = document.createElement('li');
            subcomponent_list_item.id = current_li_name;

            my_subcomponent_list.appendChild(subcomponent_list_item);

            my_subcomponent_node = document.getElementById(current_li_name);

            current_chart_name = String(current_li_name + "_chart");

            my_subcomponent_node.insertAdjacentHTML('beforeend', `
                    <div class="row">
                        <div class="col-5">
                        <em><b>Bileşen:</b></em> ${s.name} 
                        <br>
                        <br>
                        <em><b>Bileşendeki çeşnilerin bileşenin süresine olan oranları:</b></em>
                        <br>
                        <br>
                        <ul id="${s.name}_list"></ul>
                        <br>                        
                        <br>                        
                        </div>
                        <div class="col-7">
                            <canvas width="200" height="200" id="${current_chart_name}"></canvas>
                        </div>
                    </div>
                    <hr>       
            `);

            my_cesni_list = document.getElementById(s.name + '_list');

            let subcomponent_total_length = 0;

            for (const cesni of s._cesni_list) {
                subcomponent_total_length += cesni.cesni_sure_256;
            }

            for (const cesni of s._cesni_list) {

                let my_cesni_item = document.createElement('li');

                let my_sure_percentage = ((cesni.cesni_sure_256 / subcomponent_total_length) * 100);

                my_cesni_item.innerHTML = cesni.cesni_ismi + ' : % ' + my_sure_percentage; // cesni.cesni_sure_256;

                my_cesni_list.appendChild(my_cesni_item);
            }

            my_subcomponent_canvas = document.getElementById(current_chart_name).getContext('2d');

            colorArr = createColorArray(subcomponent_list.length)

            let my_chart = new Chart(my_subcomponent_canvas, {
                type: 'pie',
                data: {
                    labels: labels,
                    datasets: [{
                        data: my_percentage_data,
                        backgroundColor: colorArr,
                        borderColor: colorArr,
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    aspectRatio: 1,
                }
            });
        }

    }

    function toPercentages(arr) {
        const total = arr.reduce((a, b) => a + b, 0);
        const percentages = arr.map(x => (x / total) * 100);
        return percentages;
    }

    createNewChartForSubcomponentAddToHtml(b_list);

</script>

{% endblock scripts %}

makamproject/makam_app/templates/makam_app/home.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Anasayfa
{% endblock title %}

{% block content %}

<div class="container">

    <div class="row">

        <h1>Anasayfa</h1>

        <div class="col-6">

            {% if user.is_authenticated %}
            <h5>Hoşgeldin, {{user.get_username}}!</h5>         
            {% else %}
            <p>Sistemi kullanabilmek için lütfen giriş yapın.</p>
            {% endif %}

        </div>

        <div class="col-6">
            <img src="{% static 'itu_logo.jpg' %}" style="width: 75%; margin: 0 auto; display: block; opacity: 0.5;" alt="itu_logo">
        </div>

    </div>

</div>

{% endblock content %}

makamproject/makam_app/templates/makam_app/profile.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Profil
{% endblock title %}

{% block content %}

<div class="container">
    <h1>Oluşturduğunuz Parçalar:</h1>

    <ul>

        {% if piece_list|length == 0 %}
        <div class="row">
            <h5>Parça bulunmamaktadır.</h5>
        </div>
        {% else %}
            {% for piece in piece_list %}
            <br>
            <li>
                <div class="row">

                    <div class="col-8">{{piece}}</div>
                    <div class="col-2"><a href="{% url 'makam_app:EditPieceView' pk=piece.pk %}" class="btn btn-primary">Düzenle</a></div>
                    <div class="col-2">
                        <form action="{% url 'makam_app:delete_piece' pk=piece.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="Sil" class="btn btn-danger">
                        </form>
                    </div>

                </div>
            </li>
            <hr>
            {% endfor %}
        {% endif %}

       

    </ul>
</div>






{% endblock content %}

makamproject/makam_app/templates/makam_app/signup.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Kayıt Sayfası
{% endblock title %}

{% block content %}
<style>
    .form-group {
        margin-bottom: 1rem;
    }

    label {
        display: block;
        margin-bottom: 0.5rem;
    }

    input,
    textarea,
    select {
        width: 100%;
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    input:focus,
    textarea:focus,
    select:focus {
        outline: none;
        border-color: #80bdff;
        box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
    }

    input[type="submit"] {
        color: #fff;
        background-color: #007bff;
        border-color: #007bff;
    }

    input[type="submit"]:hover {
        background-color: #0069d9;
        border-color: #0062cc;
    }
</style>

<div class="container">

    <div class="row">
        <h2>Sisteme Kaydol:</h2>
        <div class="col-6">
            <form method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <div class="col-sm-10">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.errors %}
                        {% for error in field.errors %}
                        <p class="text-danger">{{ error }}</p>
                        {% endfor %}
                        {% endif %}
                        {% if field.help_text %}
                        <br>
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                        {% endif %}
                    </div>
                   
                </div>
                {% endfor %}
                <input type="submit" class="col-sm-10" value="Kaydol">
            </form>

        </div>

        <div class="col-6">
            <img src="{% static 'itu_logo.jpg' %}" style="width: 75%; margin: 0 auto; display: block; opacity: 0.3;" alt="itu_logo">
        </div>

    </div>

</div>


{% endblock content %}